trigger: none

resources:
  pipelines:
  - pipeline: HelloWorldBuild
    source: 'BuildPipeline'
    trigger:
      branches:
        include:
        - main

stages:
- stage: Dev
  jobs:
  - deployment: DeployToDev
    pool:
      vmImage: windows-latest
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - download: HelloWorldBuild
            artifact: drop
            displayName: 'Download Latest Build Artifact'
          - publish: $(Pipeline.Workspace)/HelloWorldBuild/drop
            artifact: DevArtifact

- stage: Stage
  jobs:
  - deployment: DeployToStage
    pool:
      vmImage: windows-latest
    environment: 'Stage'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - download: current
            artifact: DevArtifact
            displayName: 'Download Dev Artifact'
          - publish: $(Pipeline.Workspace)/DevArtifact
            artifact: StageArtifact

- stage: Prod
  jobs:
  - deployment: DeployToProd
    pool:
      vmImage: windows-latest
    environment: 'Prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
                Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
                ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
            displayName: 'Install .NET SDK'
          - download: current
            artifact: StageArtifact
            displayName: 'Download Stage Artifact'
          - publish: $(Pipeline.Workspace)/StageArtifact
            artifact: ProdArtifact

- stage: Sandbox
  jobs:
  - job: BuildAndDeploy
    pool:
      vmImage: windows-latest
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $dotnetUrl = "https://dot.net/v1/dotnet-install.ps1"
          Invoke-WebRequest -Uri $dotnetUrl -OutFile "dotnet-install.ps1"
          ./dotnet-install.ps1 -Channel 8.0 -InstallDir "$(Agent.ToolsDirectory)/dotnet"
      displayName: 'Install .NET SDK'
    - checkout: self
    - script: |
        set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
        dotnet --version
        dir
        dotnet new console -n HelloWorld
        move Program.cs HelloWorld\Program.cs
        cd HelloWorld
        dotnet build --configuration Release
        dotnet publish --configuration Release --output $(System.DefaultWorkingDirectory)/Sandbox/drop
      displayName: 'Create project, build and publish'
    - script: |
        set PATH=$(Agent.ToolsDirectory)/dotnet;%PATH%
        dotnet --version
        dotnet $(System.DefaultWorkingDirectory)/Sandbox/drop/HelloWorld.dll
      displayName: 'Run HelloWorld'